// Code generated by ent, DO NOT EDIT.

package lotterychance

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotterychance type in the database.
	Label = "lottery_chance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAvailableCount holds the string denoting the available_count field in the database.
	FieldAvailableCount = "available_count"
	// FieldTodayRechargeCount holds the string denoting the today_recharge_count field in the database.
	FieldTodayRechargeCount = "today_recharge_count"
	// FieldRechargeDate holds the string denoting the recharge_date field in the database.
	FieldRechargeDate = "recharge_date"
	// FieldLastLoginDate holds the string denoting the last_login_date field in the database.
	FieldLastLoginDate = "last_login_date"
	// Table holds the table name of the lotterychance in the database.
	Table = "lottery_chances"
)

// Columns holds all SQL columns for lotterychance fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldAvailableCount,
	FieldTodayRechargeCount,
	FieldRechargeDate,
	FieldLastLoginDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAvailableCount holds the default value on creation for the "available_count" field.
	DefaultAvailableCount int
	// DefaultTodayRechargeCount holds the default value on creation for the "today_recharge_count" field.
	DefaultTodayRechargeCount int
	// RechargeDateValidator is a validator for the "recharge_date" field. It is called by the builders before save.
	RechargeDateValidator func(string) error
	// LastLoginDateValidator is a validator for the "last_login_date" field. It is called by the builders before save.
	LastLoginDateValidator func(string) error
)

// OrderOption defines the ordering options for the LotteryChance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAvailableCount orders the results by the available_count field.
func ByAvailableCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableCount, opts...).ToFunc()
}

// ByTodayRechargeCount orders the results by the today_recharge_count field.
func ByTodayRechargeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTodayRechargeCount, opts...).ToFunc()
}

// ByRechargeDate orders the results by the recharge_date field.
func ByRechargeDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeDate, opts...).ToFunc()
}

// ByLastLoginDate orders the results by the last_login_date field.
func ByLastLoginDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginDate, opts...).ToFunc()
}
