// Code generated by ent, DO NOT EDIT.

package lotterychance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUserID, v))
}

// AvailableCount applies equality check predicate on the "available_count" field. It's identical to AvailableCountEQ.
func AvailableCount(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldAvailableCount, v))
}

// TodayRechargeCount applies equality check predicate on the "today_recharge_count" field. It's identical to TodayRechargeCountEQ.
func TodayRechargeCount(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldTodayRechargeCount, v))
}

// RechargeDate applies equality check predicate on the "recharge_date" field. It's identical to RechargeDateEQ.
func RechargeDate(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldRechargeDate, v))
}

// LastLoginDate applies equality check predicate on the "last_login_date" field. It's identical to LastLoginDateEQ.
func LastLoginDate(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldLastLoginDate, v))
}

// CountDate applies equality check predicate on the "count_date" field. It's identical to CountDateEQ.
func CountDate(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldCountDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldUserID, v))
}

// AvailableCountEQ applies the EQ predicate on the "available_count" field.
func AvailableCountEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldAvailableCount, v))
}

// AvailableCountNEQ applies the NEQ predicate on the "available_count" field.
func AvailableCountNEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldAvailableCount, v))
}

// AvailableCountIn applies the In predicate on the "available_count" field.
func AvailableCountIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldAvailableCount, vs...))
}

// AvailableCountNotIn applies the NotIn predicate on the "available_count" field.
func AvailableCountNotIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldAvailableCount, vs...))
}

// AvailableCountGT applies the GT predicate on the "available_count" field.
func AvailableCountGT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldAvailableCount, v))
}

// AvailableCountGTE applies the GTE predicate on the "available_count" field.
func AvailableCountGTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldAvailableCount, v))
}

// AvailableCountLT applies the LT predicate on the "available_count" field.
func AvailableCountLT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldAvailableCount, v))
}

// AvailableCountLTE applies the LTE predicate on the "available_count" field.
func AvailableCountLTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldAvailableCount, v))
}

// TodayRechargeCountEQ applies the EQ predicate on the "today_recharge_count" field.
func TodayRechargeCountEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldTodayRechargeCount, v))
}

// TodayRechargeCountNEQ applies the NEQ predicate on the "today_recharge_count" field.
func TodayRechargeCountNEQ(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldTodayRechargeCount, v))
}

// TodayRechargeCountIn applies the In predicate on the "today_recharge_count" field.
func TodayRechargeCountIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldTodayRechargeCount, vs...))
}

// TodayRechargeCountNotIn applies the NotIn predicate on the "today_recharge_count" field.
func TodayRechargeCountNotIn(vs ...int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldTodayRechargeCount, vs...))
}

// TodayRechargeCountGT applies the GT predicate on the "today_recharge_count" field.
func TodayRechargeCountGT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldTodayRechargeCount, v))
}

// TodayRechargeCountGTE applies the GTE predicate on the "today_recharge_count" field.
func TodayRechargeCountGTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldTodayRechargeCount, v))
}

// TodayRechargeCountLT applies the LT predicate on the "today_recharge_count" field.
func TodayRechargeCountLT(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldTodayRechargeCount, v))
}

// TodayRechargeCountLTE applies the LTE predicate on the "today_recharge_count" field.
func TodayRechargeCountLTE(v int) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldTodayRechargeCount, v))
}

// RechargeDateEQ applies the EQ predicate on the "recharge_date" field.
func RechargeDateEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldRechargeDate, v))
}

// RechargeDateNEQ applies the NEQ predicate on the "recharge_date" field.
func RechargeDateNEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldRechargeDate, v))
}

// RechargeDateIn applies the In predicate on the "recharge_date" field.
func RechargeDateIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldRechargeDate, vs...))
}

// RechargeDateNotIn applies the NotIn predicate on the "recharge_date" field.
func RechargeDateNotIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldRechargeDate, vs...))
}

// RechargeDateGT applies the GT predicate on the "recharge_date" field.
func RechargeDateGT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldRechargeDate, v))
}

// RechargeDateGTE applies the GTE predicate on the "recharge_date" field.
func RechargeDateGTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldRechargeDate, v))
}

// RechargeDateLT applies the LT predicate on the "recharge_date" field.
func RechargeDateLT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldRechargeDate, v))
}

// RechargeDateLTE applies the LTE predicate on the "recharge_date" field.
func RechargeDateLTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldRechargeDate, v))
}

// RechargeDateContains applies the Contains predicate on the "recharge_date" field.
func RechargeDateContains(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContains(FieldRechargeDate, v))
}

// RechargeDateHasPrefix applies the HasPrefix predicate on the "recharge_date" field.
func RechargeDateHasPrefix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasPrefix(FieldRechargeDate, v))
}

// RechargeDateHasSuffix applies the HasSuffix predicate on the "recharge_date" field.
func RechargeDateHasSuffix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasSuffix(FieldRechargeDate, v))
}

// RechargeDateIsNil applies the IsNil predicate on the "recharge_date" field.
func RechargeDateIsNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIsNull(FieldRechargeDate))
}

// RechargeDateNotNil applies the NotNil predicate on the "recharge_date" field.
func RechargeDateNotNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotNull(FieldRechargeDate))
}

// RechargeDateEqualFold applies the EqualFold predicate on the "recharge_date" field.
func RechargeDateEqualFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEqualFold(FieldRechargeDate, v))
}

// RechargeDateContainsFold applies the ContainsFold predicate on the "recharge_date" field.
func RechargeDateContainsFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContainsFold(FieldRechargeDate, v))
}

// LastLoginDateEQ applies the EQ predicate on the "last_login_date" field.
func LastLoginDateEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldLastLoginDate, v))
}

// LastLoginDateNEQ applies the NEQ predicate on the "last_login_date" field.
func LastLoginDateNEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldLastLoginDate, v))
}

// LastLoginDateIn applies the In predicate on the "last_login_date" field.
func LastLoginDateIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldLastLoginDate, vs...))
}

// LastLoginDateNotIn applies the NotIn predicate on the "last_login_date" field.
func LastLoginDateNotIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldLastLoginDate, vs...))
}

// LastLoginDateGT applies the GT predicate on the "last_login_date" field.
func LastLoginDateGT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldLastLoginDate, v))
}

// LastLoginDateGTE applies the GTE predicate on the "last_login_date" field.
func LastLoginDateGTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldLastLoginDate, v))
}

// LastLoginDateLT applies the LT predicate on the "last_login_date" field.
func LastLoginDateLT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldLastLoginDate, v))
}

// LastLoginDateLTE applies the LTE predicate on the "last_login_date" field.
func LastLoginDateLTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldLastLoginDate, v))
}

// LastLoginDateContains applies the Contains predicate on the "last_login_date" field.
func LastLoginDateContains(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContains(FieldLastLoginDate, v))
}

// LastLoginDateHasPrefix applies the HasPrefix predicate on the "last_login_date" field.
func LastLoginDateHasPrefix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasPrefix(FieldLastLoginDate, v))
}

// LastLoginDateHasSuffix applies the HasSuffix predicate on the "last_login_date" field.
func LastLoginDateHasSuffix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasSuffix(FieldLastLoginDate, v))
}

// LastLoginDateIsNil applies the IsNil predicate on the "last_login_date" field.
func LastLoginDateIsNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIsNull(FieldLastLoginDate))
}

// LastLoginDateNotNil applies the NotNil predicate on the "last_login_date" field.
func LastLoginDateNotNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotNull(FieldLastLoginDate))
}

// LastLoginDateEqualFold applies the EqualFold predicate on the "last_login_date" field.
func LastLoginDateEqualFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEqualFold(FieldLastLoginDate, v))
}

// LastLoginDateContainsFold applies the ContainsFold predicate on the "last_login_date" field.
func LastLoginDateContainsFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContainsFold(FieldLastLoginDate, v))
}

// CountDateEQ applies the EQ predicate on the "count_date" field.
func CountDateEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEQ(FieldCountDate, v))
}

// CountDateNEQ applies the NEQ predicate on the "count_date" field.
func CountDateNEQ(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNEQ(FieldCountDate, v))
}

// CountDateIn applies the In predicate on the "count_date" field.
func CountDateIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIn(FieldCountDate, vs...))
}

// CountDateNotIn applies the NotIn predicate on the "count_date" field.
func CountDateNotIn(vs ...string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotIn(FieldCountDate, vs...))
}

// CountDateGT applies the GT predicate on the "count_date" field.
func CountDateGT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGT(FieldCountDate, v))
}

// CountDateGTE applies the GTE predicate on the "count_date" field.
func CountDateGTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldGTE(FieldCountDate, v))
}

// CountDateLT applies the LT predicate on the "count_date" field.
func CountDateLT(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLT(FieldCountDate, v))
}

// CountDateLTE applies the LTE predicate on the "count_date" field.
func CountDateLTE(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldLTE(FieldCountDate, v))
}

// CountDateContains applies the Contains predicate on the "count_date" field.
func CountDateContains(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContains(FieldCountDate, v))
}

// CountDateHasPrefix applies the HasPrefix predicate on the "count_date" field.
func CountDateHasPrefix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasPrefix(FieldCountDate, v))
}

// CountDateHasSuffix applies the HasSuffix predicate on the "count_date" field.
func CountDateHasSuffix(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldHasSuffix(FieldCountDate, v))
}

// CountDateIsNil applies the IsNil predicate on the "count_date" field.
func CountDateIsNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldIsNull(FieldCountDate))
}

// CountDateNotNil applies the NotNil predicate on the "count_date" field.
func CountDateNotNil() predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldNotNull(FieldCountDate))
}

// CountDateEqualFold applies the EqualFold predicate on the "count_date" field.
func CountDateEqualFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldEqualFold(FieldCountDate, v))
}

// CountDateContainsFold applies the ContainsFold predicate on the "count_date" field.
func CountDateContainsFold(v string) predicate.LotteryChance {
	return predicate.LotteryChance(sql.FieldContainsFold(FieldCountDate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryChance) predicate.LotteryChance {
	return predicate.LotteryChance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryChance) predicate.LotteryChance {
	return predicate.LotteryChance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryChance) predicate.LotteryChance {
	return predicate.LotteryChance(sql.NotPredicates(p))
}
