// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
)

// LotteryChanceCreate is the builder for creating a LotteryChance entity.
type LotteryChanceCreate struct {
	config
	mutation *LotteryChanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryChanceCreate) SetCreatedAt(v time.Time) *LotteryChanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableCreatedAt(v *time.Time) *LotteryChanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryChanceCreate) SetUpdatedAt(v time.Time) *LotteryChanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableUpdatedAt(v *time.Time) *LotteryChanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LotteryChanceCreate) SetUserID(v int64) *LotteryChanceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAvailableCount sets the "available_count" field.
func (_c *LotteryChanceCreate) SetAvailableCount(v int) *LotteryChanceCreate {
	_c.mutation.SetAvailableCount(v)
	return _c
}

// SetNillableAvailableCount sets the "available_count" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableAvailableCount(v *int) *LotteryChanceCreate {
	if v != nil {
		_c.SetAvailableCount(*v)
	}
	return _c
}

// SetTodayRechargeCount sets the "today_recharge_count" field.
func (_c *LotteryChanceCreate) SetTodayRechargeCount(v int) *LotteryChanceCreate {
	_c.mutation.SetTodayRechargeCount(v)
	return _c
}

// SetNillableTodayRechargeCount sets the "today_recharge_count" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableTodayRechargeCount(v *int) *LotteryChanceCreate {
	if v != nil {
		_c.SetTodayRechargeCount(*v)
	}
	return _c
}

// SetRechargeDate sets the "recharge_date" field.
func (_c *LotteryChanceCreate) SetRechargeDate(v string) *LotteryChanceCreate {
	_c.mutation.SetRechargeDate(v)
	return _c
}

// SetNillableRechargeDate sets the "recharge_date" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableRechargeDate(v *string) *LotteryChanceCreate {
	if v != nil {
		_c.SetRechargeDate(*v)
	}
	return _c
}

// SetLastLoginDate sets the "last_login_date" field.
func (_c *LotteryChanceCreate) SetLastLoginDate(v string) *LotteryChanceCreate {
	_c.mutation.SetLastLoginDate(v)
	return _c
}

// SetNillableLastLoginDate sets the "last_login_date" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableLastLoginDate(v *string) *LotteryChanceCreate {
	if v != nil {
		_c.SetLastLoginDate(*v)
	}
	return _c
}

// SetCountDate sets the "count_date" field.
func (_c *LotteryChanceCreate) SetCountDate(v string) *LotteryChanceCreate {
	_c.mutation.SetCountDate(v)
	return _c
}

// SetNillableCountDate sets the "count_date" field if the given value is not nil.
func (_c *LotteryChanceCreate) SetNillableCountDate(v *string) *LotteryChanceCreate {
	if v != nil {
		_c.SetCountDate(*v)
	}
	return _c
}

// Mutation returns the LotteryChanceMutation object of the builder.
func (_c *LotteryChanceCreate) Mutation() *LotteryChanceMutation {
	return _c.mutation
}

// Save creates the LotteryChance in the database.
func (_c *LotteryChanceCreate) Save(ctx context.Context) (*LotteryChance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryChanceCreate) SaveX(ctx context.Context) *LotteryChance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryChanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryChanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryChanceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterychance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotterychance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AvailableCount(); !ok {
		v := lotterychance.DefaultAvailableCount
		_c.mutation.SetAvailableCount(v)
	}
	if _, ok := _c.mutation.TodayRechargeCount(); !ok {
		v := lotterychance.DefaultTodayRechargeCount
		_c.mutation.SetTodayRechargeCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryChanceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryChance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryChance.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryChance.user_id"`)}
	}
	if _, ok := _c.mutation.AvailableCount(); !ok {
		return &ValidationError{Name: "available_count", err: errors.New(`ent: missing required field "LotteryChance.available_count"`)}
	}
	if _, ok := _c.mutation.TodayRechargeCount(); !ok {
		return &ValidationError{Name: "today_recharge_count", err: errors.New(`ent: missing required field "LotteryChance.today_recharge_count"`)}
	}
	if v, ok := _c.mutation.RechargeDate(); ok {
		if err := lotterychance.RechargeDateValidator(v); err != nil {
			return &ValidationError{Name: "recharge_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.recharge_date": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastLoginDate(); ok {
		if err := lotterychance.LastLoginDateValidator(v); err != nil {
			return &ValidationError{Name: "last_login_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.last_login_date": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CountDate(); ok {
		if err := lotterychance.CountDateValidator(v); err != nil {
			return &ValidationError{Name: "count_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.count_date": %w`, err)}
		}
	}
	return nil
}

func (_c *LotteryChanceCreate) sqlSave(ctx context.Context) (*LotteryChance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryChanceCreate) createSpec() (*LotteryChance, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryChance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterychance.Table, sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterychance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterychance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotterychance.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AvailableCount(); ok {
		_spec.SetField(lotterychance.FieldAvailableCount, field.TypeInt, value)
		_node.AvailableCount = value
	}
	if value, ok := _c.mutation.TodayRechargeCount(); ok {
		_spec.SetField(lotterychance.FieldTodayRechargeCount, field.TypeInt, value)
		_node.TodayRechargeCount = value
	}
	if value, ok := _c.mutation.RechargeDate(); ok {
		_spec.SetField(lotterychance.FieldRechargeDate, field.TypeString, value)
		_node.RechargeDate = &value
	}
	if value, ok := _c.mutation.LastLoginDate(); ok {
		_spec.SetField(lotterychance.FieldLastLoginDate, field.TypeString, value)
		_node.LastLoginDate = &value
	}
	if value, ok := _c.mutation.CountDate(); ok {
		_spec.SetField(lotterychance.FieldCountDate, field.TypeString, value)
		_node.CountDate = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryChance.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryChanceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryChanceCreate) OnConflict(opts ...sql.ConflictOption) *LotteryChanceUpsertOne {
	_c.conflict = opts
	return &LotteryChanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryChanceCreate) OnConflictColumns(columns ...string) *LotteryChanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryChanceUpsertOne{
		create: _c,
	}
}

type (
	// LotteryChanceUpsertOne is the builder for "upsert"-ing
	//  one LotteryChance node.
	LotteryChanceUpsertOne struct {
		create *LotteryChanceCreate
	}

	// LotteryChanceUpsert is the "OnConflict" setter.
	LotteryChanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryChanceUpsert) SetUpdatedAt(v time.Time) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateUpdatedAt() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceUpsert) SetUserID(v int64) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateUserID() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryChanceUpsert) AddUserID(v int64) *LotteryChanceUpsert {
	u.Add(lotterychance.FieldUserID, v)
	return u
}

// SetAvailableCount sets the "available_count" field.
func (u *LotteryChanceUpsert) SetAvailableCount(v int) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldAvailableCount, v)
	return u
}

// UpdateAvailableCount sets the "available_count" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateAvailableCount() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldAvailableCount)
	return u
}

// AddAvailableCount adds v to the "available_count" field.
func (u *LotteryChanceUpsert) AddAvailableCount(v int) *LotteryChanceUpsert {
	u.Add(lotterychance.FieldAvailableCount, v)
	return u
}

// SetTodayRechargeCount sets the "today_recharge_count" field.
func (u *LotteryChanceUpsert) SetTodayRechargeCount(v int) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldTodayRechargeCount, v)
	return u
}

// UpdateTodayRechargeCount sets the "today_recharge_count" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateTodayRechargeCount() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldTodayRechargeCount)
	return u
}

// AddTodayRechargeCount adds v to the "today_recharge_count" field.
func (u *LotteryChanceUpsert) AddTodayRechargeCount(v int) *LotteryChanceUpsert {
	u.Add(lotterychance.FieldTodayRechargeCount, v)
	return u
}

// SetRechargeDate sets the "recharge_date" field.
func (u *LotteryChanceUpsert) SetRechargeDate(v string) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldRechargeDate, v)
	return u
}

// UpdateRechargeDate sets the "recharge_date" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateRechargeDate() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldRechargeDate)
	return u
}

// ClearRechargeDate clears the value of the "recharge_date" field.
func (u *LotteryChanceUpsert) ClearRechargeDate() *LotteryChanceUpsert {
	u.SetNull(lotterychance.FieldRechargeDate)
	return u
}

// SetLastLoginDate sets the "last_login_date" field.
func (u *LotteryChanceUpsert) SetLastLoginDate(v string) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldLastLoginDate, v)
	return u
}

// UpdateLastLoginDate sets the "last_login_date" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateLastLoginDate() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldLastLoginDate)
	return u
}

// ClearLastLoginDate clears the value of the "last_login_date" field.
func (u *LotteryChanceUpsert) ClearLastLoginDate() *LotteryChanceUpsert {
	u.SetNull(lotterychance.FieldLastLoginDate)
	return u
}

// SetCountDate sets the "count_date" field.
func (u *LotteryChanceUpsert) SetCountDate(v string) *LotteryChanceUpsert {
	u.Set(lotterychance.FieldCountDate, v)
	return u
}

// UpdateCountDate sets the "count_date" field to the value that was provided on create.
func (u *LotteryChanceUpsert) UpdateCountDate() *LotteryChanceUpsert {
	u.SetExcluded(lotterychance.FieldCountDate)
	return u
}

// ClearCountDate clears the value of the "count_date" field.
func (u *LotteryChanceUpsert) ClearCountDate() *LotteryChanceUpsert {
	u.SetNull(lotterychance.FieldCountDate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryChanceUpsertOne) UpdateNewValues() *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterychance.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryChanceUpsertOne) Ignore() *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryChanceUpsertOne) DoNothing() *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryChanceCreate.OnConflict
// documentation for more info.
func (u *LotteryChanceUpsertOne) Update(set func(*LotteryChanceUpsert)) *LotteryChanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryChanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryChanceUpsertOne) SetUpdatedAt(v time.Time) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateUpdatedAt() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceUpsertOne) SetUserID(v int64) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryChanceUpsertOne) AddUserID(v int64) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateUserID() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUserID()
	})
}

// SetAvailableCount sets the "available_count" field.
func (u *LotteryChanceUpsertOne) SetAvailableCount(v int) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetAvailableCount(v)
	})
}

// AddAvailableCount adds v to the "available_count" field.
func (u *LotteryChanceUpsertOne) AddAvailableCount(v int) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.AddAvailableCount(v)
	})
}

// UpdateAvailableCount sets the "available_count" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateAvailableCount() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateAvailableCount()
	})
}

// SetTodayRechargeCount sets the "today_recharge_count" field.
func (u *LotteryChanceUpsertOne) SetTodayRechargeCount(v int) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetTodayRechargeCount(v)
	})
}

// AddTodayRechargeCount adds v to the "today_recharge_count" field.
func (u *LotteryChanceUpsertOne) AddTodayRechargeCount(v int) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.AddTodayRechargeCount(v)
	})
}

// UpdateTodayRechargeCount sets the "today_recharge_count" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateTodayRechargeCount() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateTodayRechargeCount()
	})
}

// SetRechargeDate sets the "recharge_date" field.
func (u *LotteryChanceUpsertOne) SetRechargeDate(v string) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetRechargeDate(v)
	})
}

// UpdateRechargeDate sets the "recharge_date" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateRechargeDate() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateRechargeDate()
	})
}

// ClearRechargeDate clears the value of the "recharge_date" field.
func (u *LotteryChanceUpsertOne) ClearRechargeDate() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearRechargeDate()
	})
}

// SetLastLoginDate sets the "last_login_date" field.
func (u *LotteryChanceUpsertOne) SetLastLoginDate(v string) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetLastLoginDate(v)
	})
}

// UpdateLastLoginDate sets the "last_login_date" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateLastLoginDate() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateLastLoginDate()
	})
}

// ClearLastLoginDate clears the value of the "last_login_date" field.
func (u *LotteryChanceUpsertOne) ClearLastLoginDate() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearLastLoginDate()
	})
}

// SetCountDate sets the "count_date" field.
func (u *LotteryChanceUpsertOne) SetCountDate(v string) *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetCountDate(v)
	})
}

// UpdateCountDate sets the "count_date" field to the value that was provided on create.
func (u *LotteryChanceUpsertOne) UpdateCountDate() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateCountDate()
	})
}

// ClearCountDate clears the value of the "count_date" field.
func (u *LotteryChanceUpsertOne) ClearCountDate() *LotteryChanceUpsertOne {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearCountDate()
	})
}

// Exec executes the query.
func (u *LotteryChanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryChanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryChanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryChanceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryChanceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryChanceCreateBulk is the builder for creating many LotteryChance entities in bulk.
type LotteryChanceCreateBulk struct {
	config
	err      error
	builders []*LotteryChanceCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryChance entities in the database.
func (_c *LotteryChanceCreateBulk) Save(ctx context.Context) ([]*LotteryChance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryChance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryChanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryChanceCreateBulk) SaveX(ctx context.Context) []*LotteryChance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryChanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryChanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryChance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryChanceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryChanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryChanceUpsertBulk {
	_c.conflict = opts
	return &LotteryChanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryChanceCreateBulk) OnConflictColumns(columns ...string) *LotteryChanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryChanceUpsertBulk{
		create: _c,
	}
}

// LotteryChanceUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryChance nodes.
type LotteryChanceUpsertBulk struct {
	create *LotteryChanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryChanceUpsertBulk) UpdateNewValues() *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterychance.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryChance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryChanceUpsertBulk) Ignore() *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryChanceUpsertBulk) DoNothing() *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryChanceCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryChanceUpsertBulk) Update(set func(*LotteryChanceUpsert)) *LotteryChanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryChanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryChanceUpsertBulk) SetUpdatedAt(v time.Time) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateUpdatedAt() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceUpsertBulk) SetUserID(v int64) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryChanceUpsertBulk) AddUserID(v int64) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateUserID() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateUserID()
	})
}

// SetAvailableCount sets the "available_count" field.
func (u *LotteryChanceUpsertBulk) SetAvailableCount(v int) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetAvailableCount(v)
	})
}

// AddAvailableCount adds v to the "available_count" field.
func (u *LotteryChanceUpsertBulk) AddAvailableCount(v int) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.AddAvailableCount(v)
	})
}

// UpdateAvailableCount sets the "available_count" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateAvailableCount() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateAvailableCount()
	})
}

// SetTodayRechargeCount sets the "today_recharge_count" field.
func (u *LotteryChanceUpsertBulk) SetTodayRechargeCount(v int) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetTodayRechargeCount(v)
	})
}

// AddTodayRechargeCount adds v to the "today_recharge_count" field.
func (u *LotteryChanceUpsertBulk) AddTodayRechargeCount(v int) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.AddTodayRechargeCount(v)
	})
}

// UpdateTodayRechargeCount sets the "today_recharge_count" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateTodayRechargeCount() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateTodayRechargeCount()
	})
}

// SetRechargeDate sets the "recharge_date" field.
func (u *LotteryChanceUpsertBulk) SetRechargeDate(v string) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetRechargeDate(v)
	})
}

// UpdateRechargeDate sets the "recharge_date" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateRechargeDate() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateRechargeDate()
	})
}

// ClearRechargeDate clears the value of the "recharge_date" field.
func (u *LotteryChanceUpsertBulk) ClearRechargeDate() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearRechargeDate()
	})
}

// SetLastLoginDate sets the "last_login_date" field.
func (u *LotteryChanceUpsertBulk) SetLastLoginDate(v string) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetLastLoginDate(v)
	})
}

// UpdateLastLoginDate sets the "last_login_date" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateLastLoginDate() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateLastLoginDate()
	})
}

// ClearLastLoginDate clears the value of the "last_login_date" field.
func (u *LotteryChanceUpsertBulk) ClearLastLoginDate() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearLastLoginDate()
	})
}

// SetCountDate sets the "count_date" field.
func (u *LotteryChanceUpsertBulk) SetCountDate(v string) *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.SetCountDate(v)
	})
}

// UpdateCountDate sets the "count_date" field to the value that was provided on create.
func (u *LotteryChanceUpsertBulk) UpdateCountDate() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.UpdateCountDate()
	})
}

// ClearCountDate clears the value of the "count_date" field.
func (u *LotteryChanceUpsertBulk) ClearCountDate() *LotteryChanceUpsertBulk {
	return u.Update(func(s *LotteryChanceUpsert) {
		s.ClearCountDate()
	})
}

// Exec executes the query.
func (u *LotteryChanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryChanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryChanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryChanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
