// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryrecord"
)

// LotteryRecordCreate is the builder for creating a LotteryRecord entity.
type LotteryRecordCreate struct {
	config
	mutation *LotteryRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryRecordCreate) SetCreatedAt(v time.Time) *LotteryRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryRecordCreate) SetNillableCreatedAt(v *time.Time) *LotteryRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryRecordCreate) SetUpdatedAt(v time.Time) *LotteryRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryRecordCreate) SetNillableUpdatedAt(v *time.Time) *LotteryRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LotteryRecordCreate) SetUserID(v int64) *LotteryRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *LotteryRecordCreate) SetAmount(v float64) *LotteryRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *LotteryRecordCreate) SetNillableAmount(v *float64) *LotteryRecordCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *LotteryRecordCreate) SetBalanceAfter(v float64) *LotteryRecordCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *LotteryRecordCreate) SetNillableBalanceAfter(v *float64) *LotteryRecordCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *LotteryRecordCreate) SetSource(v string) *LotteryRecordCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *LotteryRecordCreate) SetNillableSource(v *string) *LotteryRecordCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// Mutation returns the LotteryRecordMutation object of the builder.
func (_c *LotteryRecordCreate) Mutation() *LotteryRecordMutation {
	return _c.mutation
}

// Save creates the LotteryRecord in the database.
func (_c *LotteryRecordCreate) Save(ctx context.Context) (*LotteryRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryRecordCreate) SaveX(ctx context.Context) *LotteryRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotteryrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := lotteryrecord.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		v := lotteryrecord.DefaultBalanceAfter
		_c.mutation.SetBalanceAfter(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := lotteryrecord.DefaultSource
		_c.mutation.SetSource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryRecord.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "LotteryRecord.amount"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "LotteryRecord.balance_after"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "LotteryRecord.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := lotteryrecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_c *LotteryRecordCreate) sqlSave(ctx context.Context) (*LotteryRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryRecordCreate) createSpec() (*LotteryRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryrecord.Table, sqlgraph.NewFieldSpec(lotteryrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotteryrecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(lotteryrecord.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(lotteryrecord.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(lotteryrecord.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryRecordCreate) OnConflict(opts ...sql.ConflictOption) *LotteryRecordUpsertOne {
	_c.conflict = opts
	return &LotteryRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryRecordCreate) OnConflictColumns(columns ...string) *LotteryRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryRecordUpsertOne{
		create: _c,
	}
}

type (
	// LotteryRecordUpsertOne is the builder for "upsert"-ing
	//  one LotteryRecord node.
	LotteryRecordUpsertOne struct {
		create *LotteryRecordCreate
	}

	// LotteryRecordUpsert is the "OnConflict" setter.
	LotteryRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryRecordUpsert) SetUpdatedAt(v time.Time) *LotteryRecordUpsert {
	u.Set(lotteryrecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryRecordUpsert) UpdateUpdatedAt() *LotteryRecordUpsert {
	u.SetExcluded(lotteryrecord.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryRecordUpsert) SetUserID(v int64) *LotteryRecordUpsert {
	u.Set(lotteryrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryRecordUpsert) UpdateUserID() *LotteryRecordUpsert {
	u.SetExcluded(lotteryrecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryRecordUpsert) AddUserID(v int64) *LotteryRecordUpsert {
	u.Add(lotteryrecord.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *LotteryRecordUpsert) SetAmount(v float64) *LotteryRecordUpsert {
	u.Set(lotteryrecord.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LotteryRecordUpsert) UpdateAmount() *LotteryRecordUpsert {
	u.SetExcluded(lotteryrecord.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *LotteryRecordUpsert) AddAmount(v float64) *LotteryRecordUpsert {
	u.Add(lotteryrecord.FieldAmount, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *LotteryRecordUpsert) SetBalanceAfter(v float64) *LotteryRecordUpsert {
	u.Set(lotteryrecord.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *LotteryRecordUpsert) UpdateBalanceAfter() *LotteryRecordUpsert {
	u.SetExcluded(lotteryrecord.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *LotteryRecordUpsert) AddBalanceAfter(v float64) *LotteryRecordUpsert {
	u.Add(lotteryrecord.FieldBalanceAfter, v)
	return u
}

// SetSource sets the "source" field.
func (u *LotteryRecordUpsert) SetSource(v string) *LotteryRecordUpsert {
	u.Set(lotteryrecord.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryRecordUpsert) UpdateSource() *LotteryRecordUpsert {
	u.SetExcluded(lotteryrecord.FieldSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryRecordUpsertOne) UpdateNewValues() *LotteryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryRecordUpsertOne) Ignore() *LotteryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryRecordUpsertOne) DoNothing() *LotteryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryRecordCreate.OnConflict
// documentation for more info.
func (u *LotteryRecordUpsertOne) Update(set func(*LotteryRecordUpsert)) *LotteryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryRecordUpsertOne) SetUpdatedAt(v time.Time) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryRecordUpsertOne) UpdateUpdatedAt() *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryRecordUpsertOne) SetUserID(v int64) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryRecordUpsertOne) AddUserID(v int64) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryRecordUpsertOne) UpdateUserID() *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *LotteryRecordUpsertOne) SetAmount(v float64) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *LotteryRecordUpsertOne) AddAmount(v float64) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LotteryRecordUpsertOne) UpdateAmount() *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *LotteryRecordUpsertOne) SetBalanceAfter(v float64) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *LotteryRecordUpsertOne) AddBalanceAfter(v float64) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *LotteryRecordUpsertOne) UpdateBalanceAfter() *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetSource sets the "source" field.
func (u *LotteryRecordUpsertOne) SetSource(v string) *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryRecordUpsertOne) UpdateSource() *LotteryRecordUpsertOne {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *LotteryRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryRecordCreateBulk is the builder for creating many LotteryRecord entities in bulk.
type LotteryRecordCreateBulk struct {
	config
	err      error
	builders []*LotteryRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryRecord entities in the database.
func (_c *LotteryRecordCreateBulk) Save(ctx context.Context) ([]*LotteryRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryRecordCreateBulk) SaveX(ctx context.Context) []*LotteryRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryRecordUpsertBulk {
	_c.conflict = opts
	return &LotteryRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryRecordCreateBulk) OnConflictColumns(columns ...string) *LotteryRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryRecordUpsertBulk{
		create: _c,
	}
}

// LotteryRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryRecord nodes.
type LotteryRecordUpsertBulk struct {
	create *LotteryRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryRecordUpsertBulk) UpdateNewValues() *LotteryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryRecordUpsertBulk) Ignore() *LotteryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryRecordUpsertBulk) DoNothing() *LotteryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryRecordCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryRecordUpsertBulk) Update(set func(*LotteryRecordUpsert)) *LotteryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryRecordUpsertBulk) SetUpdatedAt(v time.Time) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryRecordUpsertBulk) UpdateUpdatedAt() *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryRecordUpsertBulk) SetUserID(v int64) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryRecordUpsertBulk) AddUserID(v int64) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryRecordUpsertBulk) UpdateUserID() *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *LotteryRecordUpsertBulk) SetAmount(v float64) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *LotteryRecordUpsertBulk) AddAmount(v float64) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LotteryRecordUpsertBulk) UpdateAmount() *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *LotteryRecordUpsertBulk) SetBalanceAfter(v float64) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *LotteryRecordUpsertBulk) AddBalanceAfter(v float64) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *LotteryRecordUpsertBulk) UpdateBalanceAfter() *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetSource sets the "source" field.
func (u *LotteryRecordUpsertBulk) SetSource(v string) *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryRecordUpsertBulk) UpdateSource() *LotteryRecordUpsertBulk {
	return u.Update(func(s *LotteryRecordUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *LotteryRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
