// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
)

// LotteryChance is the model entity for the LotteryChance schema.
type LotteryChance struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AvailableCount holds the value of the "available_count" field.
	AvailableCount int `json:"available_count,omitempty"`
	// TodayRechargeCount holds the value of the "today_recharge_count" field.
	TodayRechargeCount int `json:"today_recharge_count,omitempty"`
	// RechargeDate holds the value of the "recharge_date" field.
	RechargeDate *string `json:"recharge_date,omitempty"`
	// LastLoginDate holds the value of the "last_login_date" field.
	LastLoginDate *string `json:"last_login_date,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryChance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterychance.FieldID, lotterychance.FieldUserID, lotterychance.FieldAvailableCount, lotterychance.FieldTodayRechargeCount:
			values[i] = new(sql.NullInt64)
		case lotterychance.FieldRechargeDate, lotterychance.FieldLastLoginDate:
			values[i] = new(sql.NullString)
		case lotterychance.FieldCreatedAt, lotterychance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryChance fields.
func (_m *LotteryChance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterychance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterychance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case lotterychance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case lotterychance.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case lotterychance.FieldAvailableCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field available_count", values[i])
			} else if value.Valid {
				_m.AvailableCount = int(value.Int64)
			}
		case lotterychance.FieldTodayRechargeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field today_recharge_count", values[i])
			} else if value.Valid {
				_m.TodayRechargeCount = int(value.Int64)
			}
		case lotterychance.FieldRechargeDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_date", values[i])
			} else if value.Valid {
				_m.RechargeDate = new(string)
				*_m.RechargeDate = value.String
			}
		case lotterychance.FieldLastLoginDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_date", values[i])
			} else if value.Valid {
				_m.LastLoginDate = new(string)
				*_m.LastLoginDate = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryChance.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryChance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryChance.
// Note that you need to call LotteryChance.Unwrap() before calling this method if this LotteryChance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryChance) Update() *LotteryChanceUpdateOne {
	return NewLotteryChanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryChance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryChance) Unwrap() *LotteryChance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryChance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryChance) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryChance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("available_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableCount))
	builder.WriteString(", ")
	builder.WriteString("today_recharge_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TodayRechargeCount))
	builder.WriteString(", ")
	if v := _m.RechargeDate; v != nil {
		builder.WriteString("recharge_date=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastLoginDate; v != nil {
		builder.WriteString("last_login_date=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// LotteryChances is a parsable slice of LotteryChance.
type LotteryChances []*LotteryChance
