// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryRecordUpdate is the builder for updating LotteryRecord entities.
type LotteryRecordUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryRecordMutation
}

// Where appends a list predicates to the LotteryRecordUpdate builder.
func (_u *LotteryRecordUpdate) Where(ps ...predicate.LotteryRecord) *LotteryRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryRecordUpdate) SetUpdatedAt(v time.Time) *LotteryRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryRecordUpdate) SetUserID(v int64) *LotteryRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryRecordUpdate) SetNillableUserID(v *int64) *LotteryRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryRecordUpdate) AddUserID(v int64) *LotteryRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *LotteryRecordUpdate) SetAmount(v float64) *LotteryRecordUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *LotteryRecordUpdate) SetNillableAmount(v *float64) *LotteryRecordUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *LotteryRecordUpdate) AddAmount(v float64) *LotteryRecordUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *LotteryRecordUpdate) SetBalanceAfter(v float64) *LotteryRecordUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *LotteryRecordUpdate) SetNillableBalanceAfter(v *float64) *LotteryRecordUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *LotteryRecordUpdate) AddBalanceAfter(v float64) *LotteryRecordUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *LotteryRecordUpdate) SetSource(v string) *LotteryRecordUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LotteryRecordUpdate) SetNillableSource(v *string) *LotteryRecordUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the LotteryRecordMutation object of the builder.
func (_u *LotteryRecordUpdate) Mutation() *LotteryRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryRecordUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := lotteryrecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryrecord.Table, lotteryrecord.Columns, sqlgraph.NewFieldSpec(lotteryrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotteryrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotteryrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(lotteryrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(lotteryrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(lotteryrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(lotteryrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(lotteryrecord.FieldSource, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryRecordUpdateOne is the builder for updating a single LotteryRecord entity.
type LotteryRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryRecordUpdateOne) SetUpdatedAt(v time.Time) *LotteryRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryRecordUpdateOne) SetUserID(v int64) *LotteryRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryRecordUpdateOne) SetNillableUserID(v *int64) *LotteryRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryRecordUpdateOne) AddUserID(v int64) *LotteryRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *LotteryRecordUpdateOne) SetAmount(v float64) *LotteryRecordUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *LotteryRecordUpdateOne) SetNillableAmount(v *float64) *LotteryRecordUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *LotteryRecordUpdateOne) AddAmount(v float64) *LotteryRecordUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *LotteryRecordUpdateOne) SetBalanceAfter(v float64) *LotteryRecordUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *LotteryRecordUpdateOne) SetNillableBalanceAfter(v *float64) *LotteryRecordUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *LotteryRecordUpdateOne) AddBalanceAfter(v float64) *LotteryRecordUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *LotteryRecordUpdateOne) SetSource(v string) *LotteryRecordUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LotteryRecordUpdateOne) SetNillableSource(v *string) *LotteryRecordUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the LotteryRecordMutation object of the builder.
func (_u *LotteryRecordUpdateOne) Mutation() *LotteryRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryRecordUpdate builder.
func (_u *LotteryRecordUpdateOne) Where(ps ...predicate.LotteryRecord) *LotteryRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryRecordUpdateOne) Select(field string, fields ...string) *LotteryRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryRecord entity.
func (_u *LotteryRecordUpdateOne) Save(ctx context.Context) (*LotteryRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryRecordUpdateOne) SaveX(ctx context.Context) *LotteryRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := lotteryrecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryRecordUpdateOne) sqlSave(ctx context.Context) (_node *LotteryRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryrecord.Table, lotteryrecord.Columns, sqlgraph.NewFieldSpec(lotteryrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryrecord.FieldID)
		for _, f := range fields {
			if !lotteryrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotteryrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotteryrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(lotteryrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(lotteryrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(lotteryrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(lotteryrecord.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(lotteryrecord.FieldSource, field.TypeString, value)
	}
	_node = &LotteryRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
