// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychance"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryChanceUpdate is the builder for updating LotteryChance entities.
type LotteryChanceUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryChanceMutation
}

// Where appends a list predicates to the LotteryChanceUpdate builder.
func (_u *LotteryChanceUpdate) Where(ps ...predicate.LotteryChance) *LotteryChanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryChanceUpdate) SetUpdatedAt(v time.Time) *LotteryChanceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryChanceUpdate) SetUserID(v int64) *LotteryChanceUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableUserID(v *int64) *LotteryChanceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryChanceUpdate) AddUserID(v int64) *LotteryChanceUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAvailableCount sets the "available_count" field.
func (_u *LotteryChanceUpdate) SetAvailableCount(v int) *LotteryChanceUpdate {
	_u.mutation.ResetAvailableCount()
	_u.mutation.SetAvailableCount(v)
	return _u
}

// SetNillableAvailableCount sets the "available_count" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableAvailableCount(v *int) *LotteryChanceUpdate {
	if v != nil {
		_u.SetAvailableCount(*v)
	}
	return _u
}

// AddAvailableCount adds value to the "available_count" field.
func (_u *LotteryChanceUpdate) AddAvailableCount(v int) *LotteryChanceUpdate {
	_u.mutation.AddAvailableCount(v)
	return _u
}

// SetTodayRechargeCount sets the "today_recharge_count" field.
func (_u *LotteryChanceUpdate) SetTodayRechargeCount(v int) *LotteryChanceUpdate {
	_u.mutation.ResetTodayRechargeCount()
	_u.mutation.SetTodayRechargeCount(v)
	return _u
}

// SetNillableTodayRechargeCount sets the "today_recharge_count" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableTodayRechargeCount(v *int) *LotteryChanceUpdate {
	if v != nil {
		_u.SetTodayRechargeCount(*v)
	}
	return _u
}

// AddTodayRechargeCount adds value to the "today_recharge_count" field.
func (_u *LotteryChanceUpdate) AddTodayRechargeCount(v int) *LotteryChanceUpdate {
	_u.mutation.AddTodayRechargeCount(v)
	return _u
}

// SetRechargeDate sets the "recharge_date" field.
func (_u *LotteryChanceUpdate) SetRechargeDate(v string) *LotteryChanceUpdate {
	_u.mutation.SetRechargeDate(v)
	return _u
}

// SetNillableRechargeDate sets the "recharge_date" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableRechargeDate(v *string) *LotteryChanceUpdate {
	if v != nil {
		_u.SetRechargeDate(*v)
	}
	return _u
}

// ClearRechargeDate clears the value of the "recharge_date" field.
func (_u *LotteryChanceUpdate) ClearRechargeDate() *LotteryChanceUpdate {
	_u.mutation.ClearRechargeDate()
	return _u
}

// SetLastLoginDate sets the "last_login_date" field.
func (_u *LotteryChanceUpdate) SetLastLoginDate(v string) *LotteryChanceUpdate {
	_u.mutation.SetLastLoginDate(v)
	return _u
}

// SetNillableLastLoginDate sets the "last_login_date" field if the given value is not nil.
func (_u *LotteryChanceUpdate) SetNillableLastLoginDate(v *string) *LotteryChanceUpdate {
	if v != nil {
		_u.SetLastLoginDate(*v)
	}
	return _u
}

// ClearLastLoginDate clears the value of the "last_login_date" field.
func (_u *LotteryChanceUpdate) ClearLastLoginDate() *LotteryChanceUpdate {
	_u.mutation.ClearLastLoginDate()
	return _u
}

// Mutation returns the LotteryChanceMutation object of the builder.
func (_u *LotteryChanceUpdate) Mutation() *LotteryChanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryChanceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryChanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryChanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryChanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryChanceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterychance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryChanceUpdate) check() error {
	if v, ok := _u.mutation.RechargeDate(); ok {
		if err := lotterychance.RechargeDateValidator(v); err != nil {
			return &ValidationError{Name: "recharge_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.recharge_date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastLoginDate(); ok {
		if err := lotterychance.LastLoginDateValidator(v); err != nil {
			return &ValidationError{Name: "last_login_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.last_login_date": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryChanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterychance.Table, lotterychance.Columns, sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterychance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterychance.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterychance.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AvailableCount(); ok {
		_spec.SetField(lotterychance.FieldAvailableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvailableCount(); ok {
		_spec.AddField(lotterychance.FieldAvailableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TodayRechargeCount(); ok {
		_spec.SetField(lotterychance.FieldTodayRechargeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTodayRechargeCount(); ok {
		_spec.AddField(lotterychance.FieldTodayRechargeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RechargeDate(); ok {
		_spec.SetField(lotterychance.FieldRechargeDate, field.TypeString, value)
	}
	if _u.mutation.RechargeDateCleared() {
		_spec.ClearField(lotterychance.FieldRechargeDate, field.TypeString)
	}
	if value, ok := _u.mutation.LastLoginDate(); ok {
		_spec.SetField(lotterychance.FieldLastLoginDate, field.TypeString, value)
	}
	if _u.mutation.LastLoginDateCleared() {
		_spec.ClearField(lotterychance.FieldLastLoginDate, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterychance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryChanceUpdateOne is the builder for updating a single LotteryChance entity.
type LotteryChanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryChanceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryChanceUpdateOne) SetUpdatedAt(v time.Time) *LotteryChanceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryChanceUpdateOne) SetUserID(v int64) *LotteryChanceUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableUserID(v *int64) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryChanceUpdateOne) AddUserID(v int64) *LotteryChanceUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAvailableCount sets the "available_count" field.
func (_u *LotteryChanceUpdateOne) SetAvailableCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.ResetAvailableCount()
	_u.mutation.SetAvailableCount(v)
	return _u
}

// SetNillableAvailableCount sets the "available_count" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableAvailableCount(v *int) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetAvailableCount(*v)
	}
	return _u
}

// AddAvailableCount adds value to the "available_count" field.
func (_u *LotteryChanceUpdateOne) AddAvailableCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.AddAvailableCount(v)
	return _u
}

// SetTodayRechargeCount sets the "today_recharge_count" field.
func (_u *LotteryChanceUpdateOne) SetTodayRechargeCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.ResetTodayRechargeCount()
	_u.mutation.SetTodayRechargeCount(v)
	return _u
}

// SetNillableTodayRechargeCount sets the "today_recharge_count" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableTodayRechargeCount(v *int) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetTodayRechargeCount(*v)
	}
	return _u
}

// AddTodayRechargeCount adds value to the "today_recharge_count" field.
func (_u *LotteryChanceUpdateOne) AddTodayRechargeCount(v int) *LotteryChanceUpdateOne {
	_u.mutation.AddTodayRechargeCount(v)
	return _u
}

// SetRechargeDate sets the "recharge_date" field.
func (_u *LotteryChanceUpdateOne) SetRechargeDate(v string) *LotteryChanceUpdateOne {
	_u.mutation.SetRechargeDate(v)
	return _u
}

// SetNillableRechargeDate sets the "recharge_date" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableRechargeDate(v *string) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetRechargeDate(*v)
	}
	return _u
}

// ClearRechargeDate clears the value of the "recharge_date" field.
func (_u *LotteryChanceUpdateOne) ClearRechargeDate() *LotteryChanceUpdateOne {
	_u.mutation.ClearRechargeDate()
	return _u
}

// SetLastLoginDate sets the "last_login_date" field.
func (_u *LotteryChanceUpdateOne) SetLastLoginDate(v string) *LotteryChanceUpdateOne {
	_u.mutation.SetLastLoginDate(v)
	return _u
}

// SetNillableLastLoginDate sets the "last_login_date" field if the given value is not nil.
func (_u *LotteryChanceUpdateOne) SetNillableLastLoginDate(v *string) *LotteryChanceUpdateOne {
	if v != nil {
		_u.SetLastLoginDate(*v)
	}
	return _u
}

// ClearLastLoginDate clears the value of the "last_login_date" field.
func (_u *LotteryChanceUpdateOne) ClearLastLoginDate() *LotteryChanceUpdateOne {
	_u.mutation.ClearLastLoginDate()
	return _u
}

// Mutation returns the LotteryChanceMutation object of the builder.
func (_u *LotteryChanceUpdateOne) Mutation() *LotteryChanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryChanceUpdate builder.
func (_u *LotteryChanceUpdateOne) Where(ps ...predicate.LotteryChance) *LotteryChanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryChanceUpdateOne) Select(field string, fields ...string) *LotteryChanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryChance entity.
func (_u *LotteryChanceUpdateOne) Save(ctx context.Context) (*LotteryChance, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryChanceUpdateOne) SaveX(ctx context.Context) *LotteryChance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryChanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryChanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryChanceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterychance.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryChanceUpdateOne) check() error {
	if v, ok := _u.mutation.RechargeDate(); ok {
		if err := lotterychance.RechargeDateValidator(v); err != nil {
			return &ValidationError{Name: "recharge_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.recharge_date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastLoginDate(); ok {
		if err := lotterychance.LastLoginDateValidator(v); err != nil {
			return &ValidationError{Name: "last_login_date", err: fmt.Errorf(`ent: validator failed for field "LotteryChance.last_login_date": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryChanceUpdateOne) sqlSave(ctx context.Context) (_node *LotteryChance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterychance.Table, lotterychance.Columns, sqlgraph.NewFieldSpec(lotterychance.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryChance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterychance.FieldID)
		for _, f := range fields {
			if !lotterychance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterychance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterychance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterychance.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterychance.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AvailableCount(); ok {
		_spec.SetField(lotterychance.FieldAvailableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvailableCount(); ok {
		_spec.AddField(lotterychance.FieldAvailableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TodayRechargeCount(); ok {
		_spec.SetField(lotterychance.FieldTodayRechargeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTodayRechargeCount(); ok {
		_spec.AddField(lotterychance.FieldTodayRechargeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RechargeDate(); ok {
		_spec.SetField(lotterychance.FieldRechargeDate, field.TypeString, value)
	}
	if _u.mutation.RechargeDateCleared() {
		_spec.ClearField(lotterychance.FieldRechargeDate, field.TypeString)
	}
	if value, ok := _u.mutation.LastLoginDate(); ok {
		_spec.SetField(lotterychance.FieldLastLoginDate, field.TypeString, value)
	}
	if _u.mutation.LastLoginDateCleared() {
		_spec.ClearField(lotterychance.FieldLastLoginDate, field.TypeString)
	}
	_node = &LotteryChance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterychance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
